### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jconnelly1** [ddbnl/office365-audit-log-collector#1] opened 2018-06-27 02:48 UTC
I receive the following error when running the collector. I read code fairly well but I cannot seem to locate the error causing the issue.

AuditLogCollector.py --general --exchange --azure_ad --sharepoint --dlp -g -gA  -gP 

Exception in thread Thread-2:
Traceback (most recent call last):
  File  line 916, in _bootstrap_inner
    self.run()
  File  line 864, in run
    self._target(*self._args, **self._kwargs)
  File "AuditLogCollector.py", line 111, in monitor_blobs_to_collect
    logging.log(level=logging.DEBUG, msg='Retrieving content blob: "{0}"'.format(blob_json['contentUri']))

TypeErrror:string indices must be integers.

I have removed all paths and IDs for security.

Thanks

**Comment by ddbnl** [comment] 2018-07-02 07:43
I'll check it out and get back to you a.s.a.p. Thanks for reporting the issue.

**Comment by ddbnl** [comment] 2018-07-02 11:09
Could you try running it again and let me know if the issue is fixed for you?

I also could not determine the exact cause, because the elements in 'blobs_to_collect'  should all be JSON dictionaries. I added a check so that the offending logging line only runs if the element is not empty and contains 'contentUri', thereby checking if this is a proper JSON response containing the URL.

**Comment by jconnelly1** [comment] 2018-07-02 13:13
Thank you!

I ran the script again and did not receive any errors.

The log file only shows one line.

INFO:root:Starting run @ 2018-07-02 08:10:11.507831

Is that normal if no errors occur?

What format does the Graylog input need to be in? I currently have it set to Syslog UDP, but I do not see anything coming through.

I appreciate your help, and your work on this script! It is good stuff.

Joel Connelly
Data Security Analyst I
[Description: cid:image001.png@01CF6E9C.42C0D140]<http://www.highlandbrokerage.com/>
3535 Grandview Parkway, Suite 600, Birmingham, AL 35243
P: 205.263.9219 | Four Digit: 1219 | support@highland.com<mailto:support@highland.com>
[Description: cid:image002.png@01CF6E9C.42C0D140]<http://blog.highlandbrokerage.com/>
Need to schedule a meeting with me? Click here.<https://calendly.com/jconnelly>
[NetworkPlus Logo Certified CE]

**Comment by jconnelly1** [comment] 2018-07-02 13:33
Also, as an aside, when I run the subscription script, none of my values change to enabled when I subscribe to the different APIs.

Joel Connelly
Data Security Analyst I
[Description: cid:image001.png@01CF6E9C.42C0D140]<http://www.highlandbrokerage.com/>
3535 Grandview Parkway, Suite 600, Birmingham, AL 35243
P: 205.263.9219 | Four Digit: 1219 | support@highland.com<mailto:support@highland.com>
[Description: cid:image002.png@01CF6E9C.42C0D140]<http://blog.highlandbrokerage.com/>
Need to schedule a meeting with me? Click here.<https://calendly.com/jconnelly>
[NetworkPlus Logo Certified CE]

**Comment by ddbnl** [comment] 2018-07-02 14:06
- For the input you can use "Raw/plaintext TCP input" with the configuration in this screenshot: https://imgur.com/a/dgJTOFd. This should have been part of the docs, so I will update those soon as well.

- About the log file: I noticed debugging was on by default, which is why the log file was so large before, it can easily grow to 100MB+. This is not a good default. In order to re-enable verbose/debug logging you can now use the '-d' switch when running the script.

- About the subscription script: it worked for me but no one else has tested it yet; I will check if I can reproduce the issue and get back to you asap.

**Comment by ddbnl** [comment] 2018-07-02 14:40
Could you try subscribing again? There were definitely errors in the script; I fixed them and am no longer able to reproduce the issue. Thanks for your interest and kind words :)

**Comment by jconnelly1** [comment] 2018-07-02 14:49
I can indeed!

I got the following when I ran it again.

Traceback (most recent call last):
  File "AuditLogSubscriber.py", line 115, in <module>
    subscriber.interactive()
  File "AuditLogSubscriber.py", line 102, in interactive
    self.set_sub_status(menu[choice - 1])
  File "AuditLogSubscriber.py", line 49, in set_sub_status
    append_url=True, get=False)
TypeError: make_api_request() got an unexpected keyword argument 'get'


I could not get anything to output to a file either on the collector. This is probably because I have not enabled them on the subscriber I hope.

Thank you for all your work on this again!

Joel Connelly
Data Security Analyst I
[Description: cid:image001.png@01CF6E9C.42C0D140]<http://www.highlandbrokerage.com/>
3535 Grandview Parkway, Suite 600, Birmingham, AL 35243
P: 205.263.9219 | Four Digit: 1219 | support@highland.com<mailto:support@highland.com>
[Description: cid:image002.png@01CF6E9C.42C0D140]<http://blog.highlandbrokerage.com/>
Need to schedule a meeting with me? Click here.<https://calendly.com/jconnelly>
[NetworkPlus Logo Certified CE]

**Comment by jconnelly1** [comment] 2018-07-02 15:17
I just got it working!

Complete user error on my part!

I neglected to update the .gitignore file.

I should be all good now.

Thank you for everything!

This is great!

Joel Connelly
Data Security Analyst I
[Description: cid:image001.png@01CF6E9C.42C0D140]<http://www.highlandbrokerage.com/>
3535 Grandview Parkway, Suite 600, Birmingham, AL 35243
P: 205.263.9219 | Four Digit: 1219 | support@highland.com<mailto:support@highland.com>
[Description: cid:image002.png@01CF6E9C.42C0D140]<http://blog.highlandbrokerage.com/>
Need to schedule a meeting with me? Click here.<https://calendly.com/jconnelly>
[NetworkPlus Logo Certified CE]

**Comment by ddbnl** [comment] 2018-07-02 17:52
Good to hear! I'll close the issue. If anything else pops up feel free to create another one.

**Closed by ddbnl** 2018-07-02 17:52 UTC
